name: Format

on:
  push:
    branches:
      - main

jobs:
  swift-format:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Tap
        run: brew install swift-format
      - name: Format
        run: make format
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Run swift-format
          branch: 'main'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
